logging:
    level:
        ltd:
            newbee:
                mall: debug

spring:
    rabbitmq:
        host: 154.12.21.42 # 主机名
        port: 5672 #端口
        username: root # 用户名
        password: root # 密码
        virtual-host: / # 虚拟主机
        connection-timeout: 1s
        template:
            retry:
                enabled: true
                multiplier: 2
                initial-interval: 1000ms
                max-attempts: 3
        publisher-confirms-types: correlated
        publisher-returns: true
        listener:
          simple:
              prefetch: 1 #设置每次只能获取一条消息 处理完才能处理下一条消息